### ISSUE TITLE
[1차 단위 테스트] 엔, 달러 입력 안 됨

### ISSUE THREAD

**Issue by hamcoding9** [wonbeeny/bbd#2]
1. Input: "고/1000엔"
2. Expected Result: 고정지출에 1000엔으로 입력됨
3. 실제 Result: 고정지출에 1000원으로 입력됨

**Comment by wonbeeny** [comment]
스프레드 시트 금액 Column 에 설정으로 소숫점 첫째자리에서 반올림해서 반영이 안 되는 것 같네요.
금액 Column 에 원화로 고정, 소숫점 첫째자리에서 반올림 고정 으로 셋팅해뒀습니다.
