### ISSUE TITLE
[1차 단위 테스트] 소숫점 입력 안 됨

### ISSUE THREAD

**Issue by hamcoding9** [wonbeeny/bbd#3]
1. Input: "고/1000.5원"
2. Expected Result: 고정지출에 1000.5원으로 입력됨
3. 실제 Result: 고정지출에 1001원으로 반올림되어 입력됨

**Comment by wonbeeny** [comment]
스프레드 시트 금액 Column 에 소숫점 첫째자리에서 반올림을 강제해둬서 그렇습니다.
