### ISSUE TITLE
[1차 단위 테스트] 음수 입력 시 에러 메시지 미출력

### ISSUE THREAD

**Issue by hamcoding9** [wonbeeny/bbd#4]
1. Input: "고/-1000원"
2. Expected Result: 에러 메시지 출력
3. 실제 Result: 음수 그대로 "-1000원" 입력됨

**Comment by wonbeeny** [comment]
수입이 있을 때 - 로 표현하기 위해 이렇게 설정했습니다.
보험금 환급과 같은 상황이 있을 수 있으니까요.
